import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const configPath = path.resolve(here, "../config/tenant.demo.json");
const outputPath = path.join(here, "seed.sql");
const config = JSON.parse(await readFile(configPath, "utf8"));

const literal = (value) => `'${String(value).replaceAll("'", "''")}'`;
const json = (value) => `${literal(JSON.stringify(value))}::jsonb`;

const sql = `-- Generated by db/generate-seed.mjs from config/tenant.demo.json.
-- Re-run: node db/generate-seed.mjs
begin;

select set_config('app.current_tenant_id', ${literal(config.tenantId)}, false);

insert into tenants (
  id, tenant_id, slug, name, legal_name, locale, fallback_locale, timezone, currency,
  branding, contact_config, avg_appointment_value_chf, baseline_no_show_rate,
  booking_tier, adapter_config, quiet_hours, review_config, messaging_config, links, services
) values (
  ${literal(config.tenantId)}::uuid,
  ${literal(config.tenantId)}::uuid,
  ${literal(config.slug)},
  ${literal(config.salonName)},
  ${literal(config.legalName)},
  ${literal(config.locale)},
  ${literal(config.fallbackLocale)},
  ${literal(config.timezone)},
  ${literal(config.currency)},
  ${json(config.branding)},
  ${json(config.contact)},
  ${Number(config.avgAppointmentValueChf).toFixed(2)},
  ${Number(config.baselineNoShowRate).toFixed(4)},
  ${literal(config.booking.tier)},
  ${json(config.booking)},
  ${json(config.quietHours)},
  ${json(config.review)},
  ${json(config.messaging)},
  ${json(config.links)},
  ${json(config.services)}
);

with source_data(source, source_weight) as (
  values ('call', 0), ('instagram', 1), ('whatsapp', 2), ('website', 3), ('google', 4)
), generated as (
  select
    row_number() over () as n,
    d::date as created_day,
    s.source
  from generate_series(current_date - 89, current_date, interval '1 day') d
  cross join lateral (
    select source from source_data
    order by ((extract(day from d)::int * 13 + source_weight * 7) % 17)
    limit case when extract(isodow from d) in (6, 7) then 2 else 3 end
  ) s
)
insert into contacts (
  id, tenant_id, ghl_contact_id, first_name, last_name, email, phone_e164,
  whatsapp_consent, email_consent, sms_consent, source, created_at
)
select
  ('20000000-0000-4000-8000-' || lpad(n::text, 12, '0'))::uuid,
  ${literal(config.tenantId)}::uuid,
  'demo-ghl-' || lpad(n::text, 4, '0'),
  (array['Lina','Sophie','Nina','Chiara','Elena','Mia','Laura','Alina','Giulia','Sara'])[((n - 1) % 10) + 1],
  (array['Meier','Keller','Frei','Rossi','Baumann','Huber','Costa','Steiner','Brunner','Graf'])[((n * 3 - 1) % 10) + 1],
  'gast' || n || '@example.test',
  '+4179000' || lpad(n::text, 4, '0'),
  (n % 5) <> 0,
  (n % 6) <> 0,
  false,
  source,
  created_day::timestamptz + interval '9 hours' + ((n % 8) * interval '47 minutes')
from generated;

with workdays as (
  select d::date as service_day,
         row_number() over (order by d) as day_no
  from generate_series(current_date - 69, current_date + 14, interval '1 day') d
  where extract(isodow from d) between 2 and 6
), slots(slot_no, local_time) as (
  values (1, time '09:00'), (2, time '10:30'), (3, time '13:00'), (4, time '14:30'), (5, time '16:00'), (6, time '17:30')
), phased_days as (
  -- phase 0 = before AIOS, 1 = rollout, 2 = AIOS live. Drives volume, no-shows, recoveries, reviews.
  select *, case when service_day < current_date - 42 then 0
                 when service_day < current_date - 24 then 1
                 else 2 end as phase
  from workdays
), appointment_rows as (
  select
    row_number() over (order by w.service_day, s.slot_no) as appointment_no,
    w.service_day,
    w.day_no,
    w.phase,
    s.slot_no,
    s.local_time,
    case (w.day_no + s.slot_no) % 4
      when 0 then 'Cut & Finish'
      when 1 then 'Balayage'
      when 2 then 'Gloss & Care'
      else 'Men''s Cut'
    end as service,
    case (w.day_no + s.slot_no) % 4 when 0 then 118 when 1 then 248 when 2 then 138 else 78 end as value_chf,
    case (w.day_no + s.slot_no) % 3 when 0 then 'Lea' when 1 then 'Mara' else 'Noemi' end as staff,
    case (w.day_no + s.slot_no) % 3
      when 0 then 'lea.atelier-nova@calendar.demo'
      when 1 then 'mara.atelier-nova@calendar.demo'
      else 'noemi.atelier-nova@calendar.demo'
    end as calendar_id
  from phased_days w
  cross join slots s
  where not (s.slot_no = 6 and (w.phase < 2 or w.day_no % 2 <> 0))
    and not (s.slot_no = 5 and w.phase = 0 and w.day_no % 4 <> 0)
), prepared as (
  select appointment_rows.*,
    (service_day + local_time) at time zone ${literal(config.timezone)}
      - (((appointment_no % 12) + 2) * interval '1 day') as booking_created_at
  from appointment_rows
), rows as (
  select prepared.*, contact.id as contact_id, contact.source
  from prepared
  join lateral (
    select c.id, c.source
    from contacts c
    where c.tenant_id = ${literal(config.tenantId)}::uuid
      and c.created_at <= prepared.booking_created_at
    order by c.created_at desc, c.id
    offset ((prepared.appointment_no * 7) % 12)
    limit 1
  ) contact on true
  where prepared.booking_created_at <= current_date::timestamptz + interval '23 hours 59 minutes'
)
insert into appointments (
  id, tenant_id, contact_id, external_id, platform, status, status_source,
  starts_at, ends_at, service, value_chf, staff, staff_calendar_id, lead_source, created_at
)
select
  ('30000000-0000-4000-8000-' || lpad(appointment_no::text, 12, '0'))::uuid,
  ${literal(config.tenantId)}::uuid,
  contact_id,
  'gcal-demo-' || lpad(appointment_no::text, 5, '0'),
  'google_calendar',
  case
    when service_day > current_date then 'booked'
    when ((day_no * 5 + slot_no) % 19) = 0 then 'cancelled'
    when phase = 0 and ((day_no * 7 + slot_no * 3) % 8) = 0 then 'no_show'
    when phase = 1 and ((day_no * 7 + slot_no * 3) % 11) = 0 then 'no_show'
    when phase = 2 and ((day_no * 7 + slot_no * 3) % 19) = 0 then 'no_show'
    else 'completed'
  end,
  case when ((day_no * 5 + slot_no) % 19) <> 0
         and ((phase = 0 and ((day_no * 7 + slot_no * 3) % 8) = 0)
           or (phase = 1 and ((day_no * 7 + slot_no * 3) % 11) = 0)
           or (phase = 2 and ((day_no * 7 + slot_no * 3) % 19) = 0))
       then 'inferred' else 'platform' end,
  (service_day + local_time) at time zone ${literal(config.timezone)},
  (service_day + local_time) at time zone ${literal(config.timezone)} +
    case when service = 'Balayage' then interval '150 minutes'
         when service = 'Gloss & Care' then interval '75 minutes'
         when service = 'Men''s Cut' then interval '45 minutes'
         else interval '60 minutes' end,
  service,
  value_chf,
  staff,
  calendar_id,
  source,
  booking_created_at
from rows;

-- Each selected no-show gets a real follow-up appointment. The new row links back to the original.
with candidates as (
  select a.*, row_number() over (order by a.starts_at) as recovery_no,
         case when extract(isodow from (a.starts_at at time zone ${literal(config.timezone)})::date + 3) between 2 and 6 then 3 else 5 end as recovery_offset
  from appointments a
  where a.tenant_id = ${literal(config.tenantId)}::uuid
    and a.status = 'no_show'
    and a.starts_at < now() - interval '4 days'
    and case when a.starts_at < current_date - 42 then mod(extract(day from a.starts_at)::int, 9) = 0
             when a.starts_at < current_date - 24 then mod(extract(day from a.starts_at)::int, 4) = 0
             else mod(extract(day from a.starts_at)::int, 2) = 0 end
)
insert into appointments (
  id, tenant_id, contact_id, external_id, platform, status, status_source,
  starts_at, ends_at, service, value_chf, staff, staff_calendar_id, lead_source,
  recovered_from_no_show_id, created_at
)
select
  ('31000000-0000-4000-8000-' || lpad(recovery_no::text, 12, '0'))::uuid,
  tenant_id,
  contact_id,
  'gcal-recovery-' || lpad(recovery_no::text, 5, '0'),
  'google_calendar',
  'completed',
  'platform',
  (((starts_at at time zone ${literal(config.timezone)})::date + recovery_offset) + time '17:30') at time zone ${literal(config.timezone)},
  (((starts_at at time zone ${literal(config.timezone)})::date + recovery_offset) + time '18:30') at time zone ${literal(config.timezone)},
  service,
  value_chf,
  staff,
  staff_calendar_id,
  lead_source,
  id,
  starts_at + interval '1 day'
from candidates;

-- Service 4.1 demo leads: recent contacts become pipeline entries with realistic statuses.
insert into leads (tenant_id, contact_id, source, channel, service_interest, urgency, preferred_time, notes, status, booked_appointment_id, created_at, updated_at)
select c.tenant_id, c.id, c.source,
  case c.source when 'instagram' then 'instagram' when 'whatsapp' then 'whatsapp' else 'email' end,
  (array['Balayage', 'Cut & Finish', 'Gloss & Care', 'Men''s Cut'])[(c.n % 4) + 1],
  (array['now', 'this_week', 'flexible'])[(c.n % 3) + 1],
  case when c.n % 2 = 0 then 'Samstagvormittag' when c.n % 5 = 0 then 'Abends nach 18:00' end,
  case when c.n % 6 = 0 then 'Möchte vorher eine Beratung.' end,
  case when a.id is not null then 'booked'
       when c.n % 7 = 0 then 'lost'
       when c.n % 3 = 0 then 'qualified'
       when c.n % 5 = 0 then 'new'
       else 'contacted' end,
  a.id,
  c.created_at + interval '4 minutes',
  c.created_at + interval '1 day'
from (
  select c.*, row_number() over (order by c.created_at desc) as n
  from contacts c
  where c.tenant_id = ${literal(config.tenantId)}::uuid and c.created_at >= now() - interval '21 days'
) c
left join lateral (
  select id from appointments a
  where a.contact_id = c.id and a.created_at >= c.created_at
  order by a.created_at limit 1
) a on true;

with contact_pool as (
  select id, row_number() over (order by created_at, id) as n, count(*) over () as total
  from contacts where tenant_id = ${literal(config.tenantId)}::uuid
), call_rows as (
  select d::date as call_day, seq,
         row_number() over (order by d, seq) as call_no
  from generate_series(current_date - 69, current_date, interval '1 day') d
  cross join lateral generate_series(1, case when extract(isodow from d) in (6,7) then 2
                                            when d < current_date - 42 then 4 else 5 end) seq
), call_flags as (
  select *, case when call_day < current_date - 42 then call_no % 4 = 0
                 when call_day < current_date - 24 then call_no % 10 = 0
                 else call_no % 40 = 0 end as missed
  from call_rows
)
insert into calls (
  tenant_id, contact_id, retell_call_id, started_at, duration_seconds, answered,
  outcome, transcript, recording_url, disclosure_played
)
select
  ${literal(config.tenantId)}::uuid,
  c.id,
  'retell-demo-' || lpad(call_no::text, 5, '0'),
  call_day::timestamptz + interval '8 hours' + (seq * interval '137 minutes'),
  case when r.missed then 0 else 72 + ((call_no * 23) % 310) end,
  not r.missed,
  case when r.missed then 'missed'
       when (call_no % 4) = 0 then 'booked'
       when (call_no % 7) = 0 then 'transferred'
       else 'inquiry' end,
  case when r.missed then null else '[Demo transcript omitted]' end,
  null,
  not r.missed
from call_flags r
join contact_pool c on c.n = (((r.call_no * 11) - 1) % c.total) + 1;

with rr as (
  select a.*, row_number() over (order by a.starts_at) as rn,
         case when a.starts_at < current_date - 42 then 0
              when a.starts_at < current_date - 24 then 1 else 2 end as phase
  from appointments a
  where a.tenant_id = ${literal(config.tenantId)}::uuid
    and a.status = 'completed'
    and a.starts_at < now()
    and case when a.starts_at < current_date - 42
               then mod(extract(day from a.starts_at)::int + extract(hour from a.starts_at)::int, 5) = 0
             when a.starts_at < current_date - 24
               then mod(extract(day from a.starts_at)::int + extract(hour from a.starts_at)::int, 2) = 0
             else mod(extract(day from a.starts_at)::int + extract(hour from a.starts_at)::int, 4) <> 0 end
), scored as (
  select rr.*,
    case when phase = 0 and rn % 4 = 0 then null
         when phase >= 1 and rn % 5 = 0 then null
         when phase = 0 and rn % 7 = 0 then 3
         when phase = 0 then 4 + case when rn % 3 = 0 then 1 else 0 end
         when phase = 1 and rn % 11 = 0 then 3
         when phase = 1 then 4 + case when rn % 2 = 0 then 1 else 0 end
         when rn % 17 = 0 then 3
         else 5 - case when rn % 3 = 0 then 1 else 0 end end as rating
  from rr
)
insert into reviews (
  tenant_id, contact_id, appointment_id, requested_at, rating, routed_to,
  received_at, gbp_review_id, private_feedback
)
select
  tenant_id, contact_id, id,
  ends_at + interval '2 hours',
  rating,
  case when rating is null then null when rating < 4 then 'private' else 'google' end,
  case when rating is null then null else ends_at + interval '1 day' + ((rn % 9) * interval '3 hours') end,
  case when rating >= 4 then 'gbp-demo-' || lpad(rn::text, 5, '0') end,
  case when rating < 4 then 'Mehr Zeit fuer die Beratung gewuenscht.' end
from scored;

insert into complaints (
  tenant_id, contact_id, source_channel, detected_category, severity, body, notified_at, resolved_at, created_at
)
select r.tenant_id, r.contact_id, 'review', 'service_feedback', 'medium', r.private_feedback,
       r.received_at + interval '3 minutes', r.received_at + interval '1 day', r.received_at
from reviews r
where r.routed_to = 'private';

insert into sequence_runs (
  tenant_id, contact_id, appointment_id, sequence_type, status, current_step,
  next_fire_at, exit_reason, metadata, started_at
)
select
  a.tenant_id, a.contact_id, a.id, 'no_show_recovery',
  case when exists (select 1 from appointments recovered where recovered.recovered_from_no_show_id = a.id)
       then 'exited' else 'completed' end,
  case when exists (select 1 from appointments recovered where recovered.recovered_from_no_show_id = a.id)
       then 'day_1' else 'day_7' end,
  null,
  case when exists (select 1 from appointments recovered where recovered.recovered_from_no_show_id = a.id)
       then 'rebooked' else 'sequence_complete' end,
  jsonb_build_object('inferred', a.status_source = 'inferred'),
  a.starts_at + interval '30 minutes'
from appointments a
where a.tenant_id = ${literal(config.tenantId)}::uuid and a.status = 'no_show';

insert into messages (
  tenant_id, contact_id, appointment_id, channel, direction, body, template_id,
  delivery_status, sent_at, created_at
)
select
  a.tenant_id, a.contact_id, a.id,
  case when step in ('t_48h', 't_2h') then 'whatsapp' else 'email' end,
  'outbound',
  '[DEMO/STUB] Appointment reminder for ' || a.service,
  step,
  'stubbed',
  case step when 't_48h' then a.starts_at - interval '48 hours'
            when 't_24h' then a.starts_at - interval '24 hours'
            else a.starts_at - interval '2 hours' end,
  case step when 't_48h' then a.starts_at - interval '48 hours'
            when 't_24h' then a.starts_at - interval '24 hours'
            else a.starts_at - interval '2 hours' end
from appointments a
cross join (values ('t_48h'), ('t_24h'), ('t_2h')) reminder(step)
where a.tenant_id = ${literal(config.tenantId)}::uuid
  and a.status in ('completed', 'no_show')
  and a.starts_at between now() - interval '60 days' and now();

insert into events (tenant_id, aggregate_type, aggregate_id, event_type, source, payload, occurred_at)
select tenant_id, 'appointment', id, 'appointment.' || status, 'seed',
       jsonb_build_object('status', status, 'staff', staff, 'value_chf', value_chf), created_at
from appointments
where tenant_id = ${literal(config.tenantId)}::uuid;

insert into events (tenant_id, aggregate_type, aggregate_id, event_type, source, payload, occurred_at)
select tenant_id, 'call', id, 'call.' || case when answered then 'answered' else 'missed' end, 'seed',
       jsonb_build_object('outcome', outcome, 'disclosure_played', disclosure_played), started_at
from calls
where tenant_id = ${literal(config.tenantId)}::uuid;

insert into kpi_daily (
  tenant_id, kpi_date, bookings_count, calls_answered, calls_missed,
  appointments_due, no_shows, no_show_recoveries,
  leads_call, leads_instagram, leads_whatsapp, leads_website, leads_google,
  bookings_call, bookings_instagram, bookings_whatsapp, bookings_website, bookings_google,
  recovered_appointments, recovered_revenue_estimate_chf,
  reviews_requested, reviews_received, rating_sum, rating_count, average_rating
)
select
  ${literal(config.tenantId)}::uuid,
  d.kpi_date,
  coalesce(booking_volume.total, 0),
  coalesce(call_stats.answered, 0),
  coalesce(call_stats.missed, 0),
  coalesce(attendance.due, 0),
  coalesce(attendance.no_shows, 0),
  coalesce(recovery_stats.recoveries, 0),
  coalesce(cohort.leads_call, 0), coalesce(cohort.leads_instagram, 0), coalesce(cohort.leads_whatsapp, 0), coalesce(cohort.leads_website, 0), coalesce(cohort.leads_google, 0),
  coalesce(cohort.bookings_call, 0), coalesce(cohort.bookings_instagram, 0), coalesce(cohort.bookings_whatsapp, 0), coalesce(cohort.bookings_website, 0), coalesce(cohort.bookings_google, 0),
  coalesce(recovery_stats.recoveries, 0),
  coalesce(recovery_stats.recoveries, 0) * ${Number(config.avgAppointmentValueChf).toFixed(2)},
  coalesce(review_stats.requested, 0),
  coalesce(review_stats.received, 0),
  coalesce(review_stats.rating_sum, 0),
  coalesce(review_stats.rating_count, 0),
  review_stats.average_rating
from (
  select generate_series(current_date - 69, current_date, interval '1 day')::date as kpi_date
) d
left join lateral (
  select count(*)::int as total
  from appointments a
  where a.tenant_id = ${literal(config.tenantId)}::uuid
    and (a.created_at at time zone ${literal(config.timezone)})::date = d.kpi_date
    and a.recovered_from_no_show_id is null
) booking_volume on true
left join lateral (
  select count(*) filter (where answered)::int as answered,
         count(*) filter (where not answered)::int as missed
  from calls c
  where c.tenant_id = ${literal(config.tenantId)}::uuid
    and (c.started_at at time zone ${literal(config.timezone)})::date = d.kpi_date
) call_stats on true
left join lateral (
  select count(*)::int as due,
         count(*) filter (where status = 'no_show')::int as no_shows
  from appointments a
  where a.tenant_id = ${literal(config.tenantId)}::uuid
    and (a.starts_at at time zone ${literal(config.timezone)})::date = d.kpi_date
    and a.status in ('completed', 'no_show')
) attendance on true
left join lateral (
  select count(*)::int as recoveries
  from appointments missed
  where missed.tenant_id = ${literal(config.tenantId)}::uuid
    and missed.status = 'no_show'
    and (missed.starts_at at time zone ${literal(config.timezone)})::date = d.kpi_date
    and exists (
      select 1
      from appointments recovered
      where recovered.tenant_id = missed.tenant_id
        and recovered.recovered_from_no_show_id = missed.id
        and recovered.status in ('booked', 'completed')
    )
) recovery_stats on true
left join lateral (
  select
    count(*) filter (where source = 'call')::int as leads_call,
    count(*) filter (where source = 'instagram')::int as leads_instagram,
    count(*) filter (where source = 'whatsapp')::int as leads_whatsapp,
    count(*) filter (where source = 'website')::int as leads_website,
    count(*) filter (where source = 'google')::int as leads_google,
    count(*) filter (where source = 'call' and has_booking)::int as bookings_call,
    count(*) filter (where source = 'instagram' and has_booking)::int as bookings_instagram,
    count(*) filter (where source = 'whatsapp' and has_booking)::int as bookings_whatsapp,
    count(*) filter (where source = 'website' and has_booking)::int as bookings_website,
    count(*) filter (where source = 'google' and has_booking)::int as bookings_google
  from (
    select c.source, exists (
      select 1
      from appointments a
      where a.tenant_id = c.tenant_id
        and a.contact_id = c.id
        and a.recovered_from_no_show_id is null
        and a.created_at >= c.created_at
    ) as has_booking
    from contacts c
    where c.tenant_id = ${literal(config.tenantId)}::uuid
      and (c.created_at at time zone ${literal(config.timezone)})::date = d.kpi_date
  ) contacts_in_cohort
) cohort on true
left join lateral (
  select count(*)::int as requested,
         count(*) filter (where received_at is not null)::int as received,
         coalesce(sum(rating) filter (where received_at is not null), 0)::numeric as rating_sum,
         count(rating) filter (where received_at is not null)::int as rating_count,
         round(avg(rating) filter (where received_at is not null), 2) as average_rating
  from reviews r
  where r.tenant_id = ${literal(config.tenantId)}::uuid
    and (r.requested_at at time zone ${literal(config.timezone)})::date = d.kpi_date
) review_stats on true
order by d.kpi_date;

commit;
`;

await writeFile(outputPath, sql);
console.log(`Wrote ${outputPath} from ${configPath}`);
