-- Generated by db/generate-seed.mjs from config/tenant.demo.json.
-- Re-run: node db/generate-seed.mjs
begin;

select set_config('app.current_tenant_id', '11111111-1111-4111-8111-111111111111', false);

insert into tenants (
  id, tenant_id, slug, name, legal_name, locale, fallback_locale, timezone, currency,
  branding, contact_config, avg_appointment_value_chf, baseline_no_show_rate,
  booking_tier, adapter_config, quiet_hours, review_config, messaging_config, links, services
) values (
  '11111111-1111-4111-8111-111111111111'::uuid,
  '11111111-1111-4111-8111-111111111111'::uuid,
  'atelier-nova-zurich',
  'Atelier Nova',
  'Atelier Nova GmbH',
  'de-CH',
  'en',
  'Europe/Zurich',
  'CHF',
  '{"logoText":"ATELIER NOVA","primary":"#173f35","accent":"#d8ff73","surface":"#f2f5f3","ink":"#10231e","fontDisplay":"Geist","fontBody":"Geist"}'::jsonb,
  '{"phone":"+41 44 555 01 24","email":"hallo@atelier-nova.example","address":"Seefeldstrasse 88, 8008 Zuerich"}'::jsonb,
  128.00,
  0.1200,
  'native',
  '{"tier":"native","platform":"google_calendar","defaultDurationMinutes":60,"slotIntervalMinutes":30,"searchRangeDays":10,"swissHolidayRegion":"ZH","staff":[{"id":"lea","name":"Lea","aliases":["lea","leah"],"calendarId":"lea.atelier-nova@calendar.demo"},{"id":"mara","name":"Mara","aliases":["mara","martha"],"calendarId":"mara.atelier-nova@calendar.demo"},{"id":"noemi","name":"Noemi","aliases":["noemi","noemie"],"calendarId":"noemi.atelier-nova@calendar.demo"}],"hours":{"monday":[],"tuesday":[{"start":"09:00","end":"18:00"}],"wednesday":[{"start":"09:00","end":"18:00"}],"thursday":[{"start":"10:00","end":"20:00"}],"friday":[{"start":"09:00","end":"18:00"}],"saturday":[{"start":"08:30","end":"16:00"}],"sunday":[]},"closureDates":["2026-12-24","2026-12-31"],"additionalHolidayDates":[]}'::jsonb,
  '{"start":"21:00","end":"08:00"}'::jsonb,
  '{"delayHours":2,"threshold":4,"gateEnabled":true,"googleReviewUrl":"https://example.com/replace-with-google-review-link","privateFeedbackUrl":"https://example.com/replace-with-private-feedback-form","ownerAlertEmail":"owner@atelier-nova.example"}'::jsonb,
  '{"mode":"stub","liveEndpointEnv":"MESSAGING_TRANSPORT_URL","liveTokenEnv":"MESSAGING_TRANSPORT_TOKEN","senderName":"Atelier Nova"}'::jsonb,
  '{"booking":"https://example.com/replace-with-booking-link","demoAgent":"tel:+41445550124","consultation":"https://example.com/replace-with-consultation-link"}'::jsonb,
  '[{"name":"Cut & Finish","durationMinutes":60,"priceChf":118},{"name":"Balayage","durationMinutes":150,"priceChf":248},{"name":"Gloss & Care","durationMinutes":75,"priceChf":138},{"name":"Men''s Cut","durationMinutes":45,"priceChf":78}]'::jsonb
);

with source_data(source, source_weight) as (
  values ('call', 0), ('instagram', 1), ('whatsapp', 2), ('website', 3), ('google', 4)
), generated as (
  select
    row_number() over () as n,
    d::date as created_day,
    s.source
  from generate_series(current_date - 89, current_date, interval '1 day') d
  cross join lateral (
    select source from source_data
    order by ((extract(day from d)::int * 13 + source_weight * 7) % 17)
    limit case when extract(isodow from d) in (6, 7) then 2 else 3 end
  ) s
)
insert into contacts (
  id, tenant_id, ghl_contact_id, first_name, last_name, email, phone_e164,
  whatsapp_consent, email_consent, sms_consent, source, created_at
)
select
  ('20000000-0000-4000-8000-' || lpad(n::text, 12, '0'))::uuid,
  '11111111-1111-4111-8111-111111111111'::uuid,
  'demo-ghl-' || lpad(n::text, 4, '0'),
  (array['Lina','Sophie','Nina','Chiara','Elena','Mia','Laura','Alina','Giulia','Sara'])[((n - 1) % 10) + 1],
  (array['Meier','Keller','Frei','Rossi','Baumann','Huber','Costa','Steiner','Brunner','Graf'])[((n * 3 - 1) % 10) + 1],
  'gast' || n || '@example.test',
  '+4179000' || lpad(n::text, 4, '0'),
  (n % 5) <> 0,
  (n % 6) <> 0,
  false,
  source,
  created_day::timestamptz + interval '9 hours' + ((n % 8) * interval '47 minutes')
from generated;

with workdays as (
  select d::date as service_day,
         row_number() over (order by d) as day_no
  from generate_series(current_date - 69, current_date + 14, interval '1 day') d
  where extract(isodow from d) between 2 and 6
), slots(slot_no, local_time) as (
  values (1, time '09:00'), (2, time '10:30'), (3, time '13:00'), (4, time '14:30'), (5, time '16:00')
), appointment_rows as (
  select
    row_number() over (order by w.service_day, s.slot_no) as appointment_no,
    w.service_day,
    w.day_no,
    s.slot_no,
    s.local_time,
    case (w.day_no + s.slot_no) % 4
      when 0 then 'Cut & Finish'
      when 1 then 'Balayage'
      when 2 then 'Gloss & Care'
      else 'Men''s Cut'
    end as service,
    case (w.day_no + s.slot_no) % 4 when 0 then 118 when 1 then 248 when 2 then 138 else 78 end as value_chf,
    case (w.day_no + s.slot_no) % 3 when 0 then 'Lea' when 1 then 'Mara' else 'Noemi' end as staff,
    case (w.day_no + s.slot_no) % 3
      when 0 then 'lea.atelier-nova@calendar.demo'
      when 1 then 'mara.atelier-nova@calendar.demo'
      else 'noemi.atelier-nova@calendar.demo'
    end as calendar_id
  from workdays w
  cross join slots s
), prepared as (
  select appointment_rows.*,
    (service_day + local_time) at time zone 'Europe/Zurich'
      - (((appointment_no % 12) + 2) * interval '1 day') as booking_created_at
  from appointment_rows
), rows as (
  select prepared.*, contact.id as contact_id, contact.source
  from prepared
  join lateral (
    select c.id, c.source
    from contacts c
    where c.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
      and c.created_at <= prepared.booking_created_at
    order by c.created_at desc, c.id
    offset ((prepared.appointment_no * 7) % 12)
    limit 1
  ) contact on true
  where prepared.booking_created_at <= current_date::timestamptz + interval '23 hours 59 minutes'
)
insert into appointments (
  id, tenant_id, contact_id, external_id, platform, status, status_source,
  starts_at, ends_at, service, value_chf, staff, staff_calendar_id, lead_source, created_at
)
select
  ('30000000-0000-4000-8000-' || lpad(appointment_no::text, 12, '0'))::uuid,
  '11111111-1111-4111-8111-111111111111'::uuid,
  contact_id,
  'gcal-demo-' || lpad(appointment_no::text, 5, '0'),
  'google_calendar',
  case
    when service_day > current_date then 'booked'
    when ((day_no * 5 + slot_no) % 19) = 0 then 'cancelled'
    when ((day_no * 7 + slot_no * 3) % 13) = 0 then 'no_show'
    else 'completed'
  end,
  case when ((day_no * 7 + slot_no * 3) % 13) = 0 then 'inferred' else 'platform' end,
  (service_day + local_time) at time zone 'Europe/Zurich',
  (service_day + local_time) at time zone 'Europe/Zurich' +
    case when service = 'Balayage' then interval '150 minutes'
         when service = 'Gloss & Care' then interval '75 minutes'
         when service = 'Men''s Cut' then interval '45 minutes'
         else interval '60 minutes' end,
  service,
  value_chf,
  staff,
  calendar_id,
  source,
  booking_created_at
from rows;

-- Each selected no-show gets a real follow-up appointment. The new row links back to the original.
with candidates as (
  select a.*, row_number() over (order by a.starts_at) as recovery_no
  from appointments a
  where a.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
    and a.status = 'no_show'
    and a.starts_at < now() - interval '8 days'
    and extract(isodow from (a.starts_at at time zone 'Europe/Zurich')::date + 7) between 2 and 6
    and mod(extract(day from a.starts_at)::int, 2) = 0
)
insert into appointments (
  id, tenant_id, contact_id, external_id, platform, status, status_source,
  starts_at, ends_at, service, value_chf, staff, staff_calendar_id, lead_source,
  recovered_from_no_show_id, created_at
)
select
  ('31000000-0000-4000-8000-' || lpad(recovery_no::text, 12, '0'))::uuid,
  tenant_id,
  contact_id,
  'gcal-recovery-' || lpad(recovery_no::text, 5, '0'),
  'google_calendar',
  'completed',
  'platform',
  (((starts_at at time zone 'Europe/Zurich')::date + 7) + time '18:30') at time zone 'Europe/Zurich',
  (((starts_at at time zone 'Europe/Zurich')::date + 7) + time '19:30') at time zone 'Europe/Zurich',
  service,
  value_chf,
  staff,
  staff_calendar_id,
  lead_source,
  id,
  starts_at + interval '1 day'
from candidates;

with contact_pool as (
  select id, row_number() over (order by created_at, id) as n, count(*) over () as total
  from contacts where tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
), call_rows as (
  select d::date as call_day, seq,
         row_number() over (order by d, seq) as call_no
  from generate_series(current_date - 69, current_date, interval '1 day') d
  cross join lateral generate_series(1, case when extract(isodow from d) in (6,7) then 2 else 4 end) seq
)
insert into calls (
  tenant_id, contact_id, retell_call_id, started_at, duration_seconds, answered,
  outcome, transcript, recording_url, disclosure_played
)
select
  '11111111-1111-4111-8111-111111111111'::uuid,
  c.id,
  'retell-demo-' || lpad(call_no::text, 5, '0'),
  call_day::timestamptz + interval '8 hours' + (seq * interval '137 minutes'),
  case when (call_no % 9) = 0 then 0 else 72 + ((call_no * 23) % 310) end,
  (call_no % 9) <> 0,
  case when (call_no % 9) = 0 then 'missed'
       when (call_no % 4) = 0 then 'booked'
       when (call_no % 7) = 0 then 'transferred'
       else 'inquiry' end,
  case when (call_no % 9) = 0 then null else '[Demo transcript omitted]' end,
  null,
  (call_no % 9) <> 0
from call_rows r
join contact_pool c on c.n = (((r.call_no * 11) - 1) % c.total) + 1;

insert into reviews (
  tenant_id, contact_id, appointment_id, requested_at, rating, routed_to,
  received_at, gbp_review_id, private_feedback
)
select
  a.tenant_id,
  a.contact_id,
  a.id,
  a.ends_at + interval '2 hours',
  case when row_number() over (order by a.starts_at) % 5 = 0 then null
       when row_number() over (order by a.starts_at) % 11 = 0 then 3
       else 4 + (row_number() over (order by a.starts_at) % 2) end,
  case when row_number() over (order by a.starts_at) % 5 = 0 then null
       when row_number() over (order by a.starts_at) % 11 = 0 then 'private'
       else 'google' end,
  case when row_number() over (order by a.starts_at) % 5 = 0 then null
       else a.ends_at + interval '1 day' + ((row_number() over (order by a.starts_at) % 9) * interval '3 hours') end,
  case when row_number() over (order by a.starts_at) % 5 <> 0
         and row_number() over (order by a.starts_at) % 11 <> 0
       then 'gbp-demo-' || lpad((row_number() over (order by a.starts_at))::text, 5, '0') end,
  case when row_number() over (order by a.starts_at) % 11 = 0 then 'Mehr Zeit fuer die Beratung gewuenscht.' end
from appointments a
where a.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
  and a.status = 'completed'
  and a.starts_at < now()
  and mod(extract(day from a.starts_at)::int + extract(hour from a.starts_at)::int, 3) = 0;

insert into complaints (
  tenant_id, contact_id, source_channel, detected_category, severity, body, notified_at, resolved_at, created_at
)
select r.tenant_id, r.contact_id, 'review', 'service_feedback', 'medium', r.private_feedback,
       r.received_at + interval '3 minutes', r.received_at + interval '1 day', r.received_at
from reviews r
where r.routed_to = 'private';

insert into sequence_runs (
  tenant_id, contact_id, appointment_id, sequence_type, status, current_step,
  next_fire_at, exit_reason, metadata, started_at
)
select
  a.tenant_id, a.contact_id, a.id, 'no_show_recovery',
  case when exists (select 1 from appointments recovered where recovered.recovered_from_no_show_id = a.id)
       then 'exited' else 'completed' end,
  case when exists (select 1 from appointments recovered where recovered.recovered_from_no_show_id = a.id)
       then 'day_1' else 'day_7' end,
  null,
  case when exists (select 1 from appointments recovered where recovered.recovered_from_no_show_id = a.id)
       then 'rebooked' else 'sequence_complete' end,
  jsonb_build_object('inferred', a.status_source = 'inferred'),
  a.starts_at + interval '30 minutes'
from appointments a
where a.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid and a.status = 'no_show';

insert into messages (
  tenant_id, contact_id, appointment_id, channel, direction, body, template_id,
  delivery_status, sent_at, created_at
)
select
  a.tenant_id, a.contact_id, a.id,
  case when step in ('t_48h', 't_2h') then 'whatsapp' else 'email' end,
  'outbound',
  '[DEMO/STUB] Appointment reminder for ' || a.service,
  step,
  'stubbed',
  case step when 't_48h' then a.starts_at - interval '48 hours'
            when 't_24h' then a.starts_at - interval '24 hours'
            else a.starts_at - interval '2 hours' end,
  case step when 't_48h' then a.starts_at - interval '48 hours'
            when 't_24h' then a.starts_at - interval '24 hours'
            else a.starts_at - interval '2 hours' end
from appointments a
cross join (values ('t_48h'), ('t_24h'), ('t_2h')) reminder(step)
where a.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
  and a.status in ('completed', 'no_show')
  and a.starts_at between now() - interval '60 days' and now();

insert into events (tenant_id, aggregate_type, aggregate_id, event_type, source, payload, occurred_at)
select tenant_id, 'appointment', id, 'appointment.' || status, 'seed',
       jsonb_build_object('status', status, 'staff', staff, 'value_chf', value_chf), created_at
from appointments
where tenant_id = '11111111-1111-4111-8111-111111111111'::uuid;

insert into events (tenant_id, aggregate_type, aggregate_id, event_type, source, payload, occurred_at)
select tenant_id, 'call', id, 'call.' || case when answered then 'answered' else 'missed' end, 'seed',
       jsonb_build_object('outcome', outcome, 'disclosure_played', disclosure_played), started_at
from calls
where tenant_id = '11111111-1111-4111-8111-111111111111'::uuid;

insert into kpi_daily (
  tenant_id, kpi_date, bookings_count, calls_answered, calls_missed,
  appointments_due, no_shows, no_show_recoveries,
  leads_call, leads_instagram, leads_whatsapp, leads_website, leads_google,
  bookings_call, bookings_instagram, bookings_whatsapp, bookings_website, bookings_google,
  recovered_appointments, recovered_revenue_estimate_chf,
  reviews_requested, reviews_received, rating_sum, rating_count, average_rating
)
select
  '11111111-1111-4111-8111-111111111111'::uuid,
  d.kpi_date,
  coalesce(booking_volume.total, 0),
  coalesce(call_stats.answered, 0),
  coalesce(call_stats.missed, 0),
  coalesce(attendance.due, 0),
  coalesce(attendance.no_shows, 0),
  coalesce(recovery_stats.recoveries, 0),
  coalesce(cohort.leads_call, 0), coalesce(cohort.leads_instagram, 0), coalesce(cohort.leads_whatsapp, 0), coalesce(cohort.leads_website, 0), coalesce(cohort.leads_google, 0),
  coalesce(cohort.bookings_call, 0), coalesce(cohort.bookings_instagram, 0), coalesce(cohort.bookings_whatsapp, 0), coalesce(cohort.bookings_website, 0), coalesce(cohort.bookings_google, 0),
  coalesce(recovery_stats.recoveries, 0),
  coalesce(recovery_stats.recoveries, 0) * 128.00,
  coalesce(review_stats.requested, 0),
  coalesce(review_stats.received, 0),
  coalesce(review_stats.rating_sum, 0),
  coalesce(review_stats.rating_count, 0),
  review_stats.average_rating
from (
  select generate_series(current_date - 69, current_date, interval '1 day')::date as kpi_date
) d
left join lateral (
  select count(*)::int as total
  from appointments a
  where a.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
    and (a.created_at at time zone 'Europe/Zurich')::date = d.kpi_date
    and a.recovered_from_no_show_id is null
) booking_volume on true
left join lateral (
  select count(*) filter (where answered)::int as answered,
         count(*) filter (where not answered)::int as missed
  from calls c
  where c.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
    and (c.started_at at time zone 'Europe/Zurich')::date = d.kpi_date
) call_stats on true
left join lateral (
  select count(*)::int as due,
         count(*) filter (where status = 'no_show')::int as no_shows
  from appointments a
  where a.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
    and (a.starts_at at time zone 'Europe/Zurich')::date = d.kpi_date
    and a.status in ('completed', 'no_show')
) attendance on true
left join lateral (
  select count(*)::int as recoveries
  from appointments missed
  where missed.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
    and missed.status = 'no_show'
    and (missed.starts_at at time zone 'Europe/Zurich')::date = d.kpi_date
    and exists (
      select 1
      from appointments recovered
      where recovered.tenant_id = missed.tenant_id
        and recovered.recovered_from_no_show_id = missed.id
        and recovered.status in ('booked', 'completed')
    )
) recovery_stats on true
left join lateral (
  select
    count(*) filter (where source = 'call')::int as leads_call,
    count(*) filter (where source = 'instagram')::int as leads_instagram,
    count(*) filter (where source = 'whatsapp')::int as leads_whatsapp,
    count(*) filter (where source = 'website')::int as leads_website,
    count(*) filter (where source = 'google')::int as leads_google,
    count(*) filter (where source = 'call' and has_booking)::int as bookings_call,
    count(*) filter (where source = 'instagram' and has_booking)::int as bookings_instagram,
    count(*) filter (where source = 'whatsapp' and has_booking)::int as bookings_whatsapp,
    count(*) filter (where source = 'website' and has_booking)::int as bookings_website,
    count(*) filter (where source = 'google' and has_booking)::int as bookings_google
  from (
    select c.source, exists (
      select 1
      from appointments a
      where a.tenant_id = c.tenant_id
        and a.contact_id = c.id
        and a.recovered_from_no_show_id is null
        and a.created_at >= c.created_at
    ) as has_booking
    from contacts c
    where c.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
      and (c.created_at at time zone 'Europe/Zurich')::date = d.kpi_date
  ) contacts_in_cohort
) cohort on true
left join lateral (
  select count(*)::int as requested,
         count(*) filter (where received_at is not null)::int as received,
         coalesce(sum(rating) filter (where received_at is not null), 0)::numeric as rating_sum,
         count(rating) filter (where received_at is not null)::int as rating_count,
         round(avg(rating) filter (where received_at is not null), 2) as average_rating
  from reviews r
  where r.tenant_id = '11111111-1111-4111-8111-111111111111'::uuid
    and (r.requested_at at time zone 'Europe/Zurich')::date = d.kpi_date
) review_stats on true
order by d.kpi_date;

commit;
